# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Scott Friedman and Project Contributors

# Basic Slurm Cluster Configuration
# This configuration describes a small Slurm cluster with basic GPU-equipped nodes

# Cluster Specification
nodes: 4                     # Number of nodes in the cluster
node_type: "basic_gpu"       # Type of nodes (basic_cpu, basic_gpu, highend_gpu, jetson_cluster, custom)
power_cost: 0.12             # Cost per kWh in USD
amortization_period: 1095    # Hardware amortization period in days (3 years)
maintenance_factor: 0.1      # Annual maintenance cost as fraction of hardware cost
utilization_factor: 0.7      # Average cluster utilization
network_cost: 5000.0         # Network infrastructure cost (USD)
admin_cost_per_year: 10000.0 # System administrator cost per year (USD)
currency: "USD"

# Note: Since we're using a predefined node type (basic_gpu), the following 
# node configuration is informational only - it matches what's defined in the system.
# These values are used automatically:
#
# Node configuration for basic_gpu:
# - cost: 3000.0 USD per node
# - power_watts: 300.0 watts per node
# - has_gpu: true
# - memory_gb: 64 GB per node
# - cores: 16 CPU cores per node
# - gpu_type: NVIDIA T4
# - gpus_per_node: 1